name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Set env
      run: |
        python3 -m venv env
        ln -s env/bin/activate
    - name: Install dependencies
      run: |
        . activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        pip install -e .
        pip wheel .
    - name: Test with pytest
      run: |
        . activate
        pip install pytest
        py.test tests
